<?php
/* Popup Image Size */
    if (strstr($_lightboxConfig['popupImageSize'], '_')) {
        $popupImageSize = explode('_', $_lightboxConfig['popupImageSize'], 2);
    } else {
        $popupImageSize = array(0, 0);
    }?>

<a href="<?php echo Mage::helper('easylightbox/image')
            ->init($this->imageAttributes['imagepath'])
            ->resize($this->imageAttributes['imagelightboxwidth'], $this->imageAttributes['imagelightboxheight']); ?>"
    rel="lightbox[<?php echo $this->imageAttributes['imagegroup']; ?>]"
    title="<?php echo $this->imageAttributes['imagetitle']; ?>"
    onclick="return false;">
    <?php echo $this->imageAttributes['imagetitle']; ?>
</a>